// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrzcFL1fpnN_Og8SGEAPHd40WmFB-pGxw',
    appId: '1:300374215771:web:660f76fdcf068bd602437e',
    messagingSenderId: '300374215771',
    projectId: 'mariamajo-46470',
    authDomain: 'mariamajo-46470.firebaseapp.com',
    storageBucket: 'mariamajo-46470.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZgtdy2WMl7g_OhtDAS4_wntbCT6g-S6E',
    appId: '1:300374215771:android:df1fd8c501a53c8b02437e',
    messagingSenderId: '300374215771',
    projectId: 'mariamajo-46470',
    storageBucket: 'mariamajo-46470.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4UZGuAYP6QMFJyoJs5lSI0p1XlDJvlRw',
    appId: '1:300374215771:ios:eb896e6264a598d502437e',
    messagingSenderId: '300374215771',
    projectId: 'mariamajo-46470',
    storageBucket: 'mariamajo-46470.appspot.com',
    iosBundleId: 'com.Maria.proyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4UZGuAYP6QMFJyoJs5lSI0p1XlDJvlRw',
    appId: '1:300374215771:ios:83f814c3b19f86fc02437e',
    messagingSenderId: '300374215771',
    projectId: 'mariamajo-46470',
    storageBucket: 'mariamajo-46470.appspot.com',
    iosBundleId: 'com.Maria.proyecto.RunnerTests',
  );
}
